<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
//$config['base_url'] = 'http://'.$_SERVER['HTTP_HOST'].'/bingos_credifinanciera/';
$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$config['base_url'] .= "://".$_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'spanish';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-@=';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
// cambio para diferenciar
$config['encryption_key'] = 'gzgKaRTpdg7eAzsMXXbrAUQv7XthGo5c';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/

$config['sess_driver'] = 'files';

// cambio para diferenciar
$config['sess_cookie_name'] = 'ci_bingo_grupoK_bpt_session';

$config['sess_expiration'] = 7200;
$config['sess_encrypt_cookie'] = TRUE;  // set from false to TRUE
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

// $config['sess_driver'] = 'redis';
// $config['sess_cookie_name'] = 'ci_bingo_televid_bpt_session';
// $config['sess_expiration'] = 7200;
// $config['sess_encrypt_cookie'] = TRUE;  // set from false to TRUE
// // $config['sess_save_path'] = NULL;
// $config['sess_save_path'] = 'tcp://cache-small.ehtlfl.0001.use1.cache.amazonaws.com:6379?weight=1&read_timeout=2.5';
// // $config['sess_save_path'] = 'memcached-emtelco.ehtlfl.cfg.use1.cache.amazonaws.com:11211';
// $config['sess_match_ip'] = FALSE;
// $config['sess_time_to_update'] = 300;
// $config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
//cambio
$config['csrf_token_name'] = 'csrf_grupoK_tk_name';
$config['csrf_cookie_name'] = 'csrf_grupoK_cookie_name';

$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';
	
/*
* Load My own MY_Controllers
*/
/*function my_own_controllers($class) {
  if (strpos($class, 'CI_') !== 0)
  {
    if (is_readable(APPPATH . 'core/' . $class . '.php'))
    {
      require_once(APPPATH . 'core/' . $class . '.php');
    }
  }
}
 
spl_autoload_register('my_own_controllers');*/

//ini_set('max_execution_time', 0); 
//ini_set('memory_limit','2048M');
	// Create customized config variables
	$config['web_Address']= 'https://xpell.tech/';
	$config['title']= 'CodeIgniter Global Variable';

	/* Constants: 
	* you can change these values at will
	*/
	$config['date_lastmod'] = "28 June 20";
	$config['version='] = " v 1.5";
	$config['bingoletters'] = array("B", "I", "N", "G", "O");
	//$patternkeywords = array("Normal","Four Corners","Cross-Shaped","T-Shaped","X-Shaped","+ Shaped","Z-Shaped", "N-Shaped", "Box Shaped", "Square Shaped","Full Card");
	$config['patternkeywords'] = array("Clasico","Cuatro Esquinas","Forma Cruz","Forma T","Forma X","Forma +","Forma Z", "Forma N", "Caja", "Cuadrado","Completo");

	/* This constant allows one to run a modified bingo up to 50 or 100. 
	* Note, the value must be a multiple of 5 (because there are 5 columns)
	* Each column will allow a subset of this number; i.e. with a standard bingo of 75, 
	* numbers 1-15 will only ever be found within column 1.
	* Note: if you generate a set of card with a given maxNumber, and then attempt to 
	* open the set of cards with a new maxNumber, unexpected results will occur
	* Ensure you set this value to the set's original value.
	*/
	$config['maxNumber'] = 75; 

	//internal constant - do not modify
	$config['maxColumnNumber'] = $config['maxNumber']/5;

	/* This is the maximum number of Bingo cards generated.  There is no theorical limit,
	* but you should be aware that each card is approx 1.5k in size when the set
	* is written to the Hard Disk.  Therefore, the execution time will slow down rapidly
	* with very large numbers.  The set is rewritten each time a number is drawn.
	* Ensure you adjust your script maximum execution time and memory usage in php.ini
	* if required.
	*/
	$config['MAX_LIMIT'] = 2000;


	$config['freesquare'] = 1;


	$config['pagetitleconfig']='Bingo virtual';

	//if pagetitleconfig empty, set to version number
	$config['pagetitle'] =($config['pagetitleconfig'] =='')?$config['version=']:$config['pagetitleconfig'];

	/* This parameter allows the user to choose the winning criterias, according to the
	* following codes:
	*
	* 0: regular Bingo rules (any row, any column or any diagonal)
	* 1: full card
	* 2: square (perimeter)
	* 3: cross (squares I-0, N-All, G-0)
	* 4: T shape (squares All-0, N-All)
	* 5: Z shape (squares All-0, All-4, G-1, N-2, I-3)
	* 6: N shape (squares B-All, O-All, I-3, N-2, G-1)
	* 7: + shape (squares N-All, All-2)
	* 8: X shape (two diagonals)
	* 9: Box shaped (all but perimeter)
	* 10: User-defined winning pattern
	*
	* NOTE: Changing the winning pattern in the middle of a game will produce undesired results
	*/
	$config['winningpattern0']='on';// regular Bingo rules (any row, any column or any diagonal)
	$config['winningpattern1']='';// 4 courners
	$config['winningpattern2']='';// cross
	$config['winningpattern3']='on';// T
	$config['winningpattern4']='';// X
	$config['winningpattern5']='';// +
	$config['winningpattern6']='';// Z
	$config['winningpattern7']='';// N
	$config['winningpattern8']='';// Box shaped
	$config['winningpattern9']='';// square (perimeter)
	$config['winningpattern10']='on';// full card

	//$config['winningpatternarray'] = array ($config['winningpattern0'],$config['winningpattern1'], $config['winningpattern2'], $config['winningpattern3'], $config['winningpattern4'], $config['winningpattern5'], $config['winningpattern6'], $config['winningpattern7'], $config['winningpattern8'], $config['winningpattern9'], $config['winningpattern10']);

	/* Name File
	* The game can read a list of names from a text file and display the names on each of the cards.
	* This feature is ideal for people that would like to customize the cards by printing each
	* person's name on the cards.  The file name must be a text file without blank lines name
	* names.A.dat where A is the applicable setID.  If the number of names is smaller than
	* the number of generated cards, the remaining cards will not have a name.  If the number
	* of names is greater than the number of cards, the remaining names will not be considered.
	*/
	$config['namefile']='';

	/* Print Rules
	* Bingoware will insert a rules page between each card when viewing for printing is this option
	* is selected.  The rules file must be called rules.txt and is best used when your printer
	* is set to print double-sided
	*/
	$config['printrules']='';


	/* Draw Mode
	* The game play mode can be "automatic" or "manual", and indicates how the random bingo numbers
	* are generated.  For Bingoware to draw the numbers for you, use "automatic".  If you are
	* using a different physical device to draw the numbers for you, the "manual" setting will
	* let you enter the drawn numbers into Bingoware so that you can still discover which are
	* the winning cards.
	* Changing of this setting should be done from the configure menu item.
	*/
	$config['drawmode']='manual';

	/* Four Per Page
	* When printing the cards, you have the otion of printing only one card per page or printing
	* four cards per page.  The rest of the program is unaffected.  The only difference is seen
	* when printing the cards, i.e., show all.
	*/
	$config['fourperpage']='';

	/* View header
	* This variable may contain HTML and will be printed at the top of each
	* page viewed (when viewing one card)
	* You should ensure to close your HTML tags so you do not disrupt the display
	* of the cards.
	*/
	$config['viewheader']='<center><b><font size="+4">B I N G O</font></b></center>';

	/* View footer
	* This variable may contain HTML and will be printed at the bottom of each
	* page viewed (when viewing one card)
	* You should ensure to close your HTML tags so you do not disrupt the display
	* of the cards.
	*/
	$config['viewfooter']='<center><b>Created with Bingoware 1.5</b><br><br><a href="javascript:window.close();">close window</a></center>';


	/* Print header
	* This variable may contain HTML and will be printed at the top of each
	* page (when viewing all cards)
	* You should ensure to close your HTML tags so you do not disrupt the display
	* of the cards.
	*/
	$config['printheader']='<center><b><font size="+6">Bingo Card</font></b></center>';


	/* Print footer
	* This variable may contain HTML and will be printed at the bottom of each
	* page (when viewing all cards)
	* You should ensure to close your HTML tags so you do not disrupt the display
	* of the cards.
	*/
	$config['printfooter']='<center><b><font size="-1">Created with Bingoware 1.5</font></b></center>';


	/* color settings
	* Several users have expressed their difficulty in changing font colours and background colors for display
	* and printing of the cards. Fear no more!  You can change the colours right from the configuration page now.
	*
	*/
	$config['primary_btn_color']='#fa7d00';
	$config['primary_btn_font_color']='#fff';
	$config['nav_bg_color']='#fa7d00';
	$config['nav_font_bg_color']='#fff';
	$config['login_img_bg_color']='#fa7d00';
	$config['banner_bg_color']='#fa7d00';
	$config['sidebar_bg_color']='#fa7d00';
	$config['sidebar_font_color']='#fff';
	$config['main_font_color']='#fa7d00';
	$config['card_font_color']='#fa7d00';
	$config['card_bg_color']='#fff';
	$config['card_number_bg_color']='#fff';
	$config['card_selected_font_color']='#fff';
	$config['card_selected_bg_color']='#fa7d00';
	$config['card_selected_border_color']='#fa7d00';
	$config['host_bg_color']='#fff';
	$config['host_font_color']='#6c6c6c';
	$config['host_bingo_font_color']='#000';
	$config['host_ball_font_color']='#fa7d00';
	$config['host_drawn_ball_font_color']='#fff';


	//Number of users in bingo registered in DB
	// $numbercards = 10;

	$config['draw_modes'] = array("Todas las balotas", "Solo balotas de la B", "Solo balotas de la I", "Solo balotas de la N", "Solo balotas de la G", "Solo balotas de la O");
	//Soporte WP
	$config['supportnumber'] = '573233321938';
	// true = ID - False = Correo
	$config['usenumberid'] = TRUE;
	//manual Increment
	$config['room'] = 190;